/*
 * InventoryDesktopApp.java
 *
 * 
 */

package compcourseenterpriseproject;

import CompCourse.UserSessionBeanRemote;
import javax.ejb.EJB;
import CompCourse.Inventory;
import CompCourse.User;
import CompCourse.Cart;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JLabel;
import java.awt.Font;

/**
 *
 * @author  Edgars
 */
public class InventoryDesktopApp extends javax.swing.JFrame {

    @EJB(name = "userSess")
    private static UserSessionBeanRemote userSess;

    /** Creates new form InventoryDesktopApp */
    public InventoryDesktopApp() {
        initComponents();
        EnableDisableCtrls(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContentPane = new javax.swing.JPanel();
        jLogInPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jInventoryChangePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textIdCreate = new javax.swing.JTextField();
        textDescriptionCreate = new javax.swing.JTextField();
        textPriceCreate = new javax.swing.JTextField();
        textCountCreate = new javax.swing.JTextField();
        textIdReserve = new javax.swing.JTextField();
        textCountReserve = new javax.swing.JTextField();
        textDescriptionSearch = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        textIdReserve3 = new javax.swing.JTextField();
        btnReserve3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jInventoryChangePanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textIdCreateUser = new javax.swing.JTextField();
        textFname = new javax.swing.JTextField();
        textLname = new javax.swing.JTextField();
        textDeleteUserID = new javax.swing.JTextField();
        textSearchName = new javax.swing.JTextField();
        btnCreateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnSearchName = new javax.swing.JButton();
        btnSearchLname = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        textSearchLname = new javax.swing.JTextField();
        btnShowAll1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jInventoryInfoPanel = new javax.swing.JPanel();
        btnShowAll = new javax.swing.JButton();
        btnCalcTotal = new javax.swing.JButton();
        btnCalcBalance = new javax.swing.JButton();
        btnCalcReserved = new javax.swing.JButton();
        jInventoryChangePanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        textIdCreateCart = new javax.swing.JTextField();
        textCreateCartCount = new javax.swing.JTextField();
        textSearchCartInv = new javax.swing.JTextField();
        btnCreateCart = new javax.swing.JButton();
        btnSearchCartInv = new javax.swing.JButton();
        textIdDeleteCartID = new javax.swing.JTextField();
        btnDeleteCart = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textSearchCartUser = new javax.swing.JTextField();
        btnSearchCartUser = new javax.swing.JButton();
        textIdCreateCartUserID = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textIdCreateCartInvID = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnGetAllCarts = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        textBuyUserID = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Component Course EJB Demo Project");
        setResizable(false);

        jContentPane.setLayout(new javax.swing.BoxLayout(jContentPane, javax.swing.BoxLayout.Y_AXIS));

        jLogInPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        btnLogIn.setText("LogIn");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLogInPanelLayout = new javax.swing.GroupLayout(jLogInPanel);
        jLogInPanel.setLayout(jLogInPanelLayout);
        jLogInPanelLayout.setHorizontalGroup(
            jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogInPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLogInPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFirstName))
                    .addGroup(jLogInPanelLayout.createSequentialGroup()
                        .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLogInPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textLastName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLogInPanelLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(107, 107, 107))
        );
        jLogInPanelLayout.setVerticalGroup(
            jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLogInPanelLayout.createSequentialGroup()
                .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLogInPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addGroup(jLogInPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnLogOut))
                .addContainerGap())
        );

        jContentPane.add(jLogInPanel);

        jInventoryChangePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("ID");

        jLabel4.setText("Description");

        jLabel5.setText("Price");

        jLabel6.setText("Count");

        jLabel7.setText("ID");

        jLabel8.setText("Res. Count");

        jLabel9.setText("Search Part by Descr.:");

        btnCreate.setText("Create/AddQ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnReserve.setText("Reserve");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        textIdReserve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdReserve3ActionPerformed(evt);
            }
        });

        btnReserve3.setText("Delete Part");
        btnReserve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserve3ActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("Part ID");

        javax.swing.GroupLayout jInventoryChangePanelLayout = new javax.swing.GroupLayout(jInventoryChangePanel);
        jInventoryChangePanel.setLayout(jInventoryChangePanelLayout);
        jInventoryChangePanelLayout.setHorizontalGroup(
            jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                        .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textIdCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel4)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6))
                            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                                .addComponent(textDescriptionCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textIdReserve, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPriceCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCountReserve)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textCountCreate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel7))
                    .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(textDescriptionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInventoryChangePanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIdReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReserve3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jInventoryChangePanelLayout.setVerticalGroup(
            jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDescriptionCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPriceCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCountCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addGap(19, 19, 19)
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCountReserve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve))
                .addGap(17, 17, 17)
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textDescriptionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jInventoryChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdReserve3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve3)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jContentPane.add(jInventoryChangePanel);

        jInventoryChangePanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("ID");

        jLabel11.setText("First Name");

        jLabel12.setText("Last Name");

        jLabel14.setText("ID");

        jLabel16.setText("Search User First Name:");

        btnCreateUser.setText("Create/AddQ");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnSearchName.setText("Search");
        btnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNameActionPerformed(evt);
            }
        });

        btnSearchLname.setText("Search");
        btnSearchLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLnameActionPerformed(evt);
            }
        });

        jLabel17.setText("Search User Last Name:");

        btnShowAll1.setText("Get All Users");
        btnShowAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAll1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText("User Management");
        jLabel25.setToolTipText("");

        javax.swing.GroupLayout jInventoryChangePanel1Layout = new javax.swing.GroupLayout(jInventoryChangePanel1);
        jInventoryChangePanel1.setLayout(jInventoryChangePanel1Layout);
        jInventoryChangePanel1Layout.setHorizontalGroup(
            jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                            .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(textIdCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textFname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel11))))
                                .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel12))
                                .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textLname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCreateUser)))
                            .addGap(0, 2, Short.MAX_VALUE)))
                    .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSearchLname, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnSearchLname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnShowAll1)
                            .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textDeleteUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInventoryChangePanel1Layout.setVerticalGroup(
            jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanel1Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDeleteUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textSearchLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowAll1))
        );

        jInventoryInfoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnShowAll.setText("GetAllParts");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        btnCalcTotal.setText("GetTotal");
        btnCalcTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcTotalActionPerformed(evt);
            }
        });

        btnCalcBalance.setText("GetBalance");
        btnCalcBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcBalanceActionPerformed(evt);
            }
        });

        btnCalcReserved.setText("GetReserved");
        btnCalcReserved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcReservedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInventoryInfoPanelLayout = new javax.swing.GroupLayout(jInventoryInfoPanel);
        jInventoryInfoPanel.setLayout(jInventoryInfoPanelLayout);
        jInventoryInfoPanelLayout.setHorizontalGroup(
            jInventoryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryInfoPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnShowAll)
                .addGap(18, 18, 18)
                .addComponent(btnCalcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcReserved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInventoryInfoPanelLayout.setVerticalGroup(
            jInventoryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInventoryInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcTotal)
                    .addComponent(btnShowAll)
                    .addComponent(btnCalcBalance)
                    .addComponent(btnCalcReserved)))
        );

        jInventoryChangePanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("ID");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Cart");

        jLabel22.setText("Search by Inv ID:");

        btnCreateCart.setText("Create/AddQ");
        btnCreateCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCartActionPerformed(evt);
            }
        });

        btnSearchCartInv.setText("Search");
        btnSearchCartInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCartInvActionPerformed(evt);
            }
        });

        textIdDeleteCartID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdDeleteCartIDActionPerformed(evt);
            }
        });

        btnDeleteCart.setText("Delete Item from Cart");
        btnDeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCartActionPerformed(evt);
            }
        });

        jLabel26.setText("Part ID");

        jLabel23.setText("Search User Items:");

        btnSearchCartUser.setText("Search");
        btnSearchCartUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCartUserActionPerformed(evt);
            }
        });

        jLabel21.setText("User ID");

        jLabel27.setText("Inv ID");

        jLabel28.setText("Count");

        btnGetAllCarts.setText("Get ALL Cart Data Items");
        btnGetAllCarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllCartsActionPerformed(evt);
            }
        });

        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        jLabel29.setText("User ID");

        javax.swing.GroupLayout jInventoryChangePanel2Layout = new javax.swing.GroupLayout(jInventoryChangePanel2);
        jInventoryChangePanel2.setLayout(jInventoryChangePanel2Layout);
        jInventoryChangePanel2Layout.setHorizontalGroup(
            jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textIdCreateCart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel21))
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textIdCreateCartUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textIdCreateCartInvID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCreateCartCount, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreateCart)
                                .addGap(229, 229, 229))
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(109, 109, 109)
                                .addComponent(btnGetAllCarts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(textSearchCartInv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchCartInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(textSearchCartUser, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchCartUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jLabel26))
                                            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                                .addComponent(textBuyUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuy)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(textIdDeleteCartID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jInventoryChangePanel2Layout.setVerticalGroup(
            jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryChangePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateCart, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCreateCartCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdCreateCartInvID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdCreateCartUserID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIdCreateCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetAllCarts))
                .addGap(18, 18, 18)
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textSearchCartUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCartUser))
                .addGap(5, 5, 5)
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(textSearchCartInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCartInv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInventoryChangePanel2Layout.createSequentialGroup()
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textIdDeleteCartID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteCart)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInventoryChangePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInventoryChangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBuyUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuy))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jInventoryChangePanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInventoryInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInventoryChangePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInventoryChangePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInventoryInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jInventoryChangePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 // enable / disable visual controls
private void EnableDisableCtrls(boolean en_ds) {
	    btnLogOut.setEnabled(en_ds);
	    textIdCreate.setEnabled(en_ds);
	    textDescriptionCreate.setEnabled(en_ds);
	    textPriceCreate.setEnabled(en_ds);
	    textCountCreate.setEnabled(en_ds);
	    btnCreate.setEnabled(en_ds);
	    textIdReserve.setEnabled(en_ds);
	    textCountReserve.setEnabled(en_ds);
	    btnReserve.setEnabled(en_ds);
	    textDescriptionSearch.setEnabled(en_ds);
	    btnSearch.setEnabled(en_ds);
	    btnShowAll.setEnabled(en_ds);
	    btnCalcTotal.setEnabled(en_ds);
	    btnCalcReserved.setEnabled(en_ds);
	    btnCalcBalance.setEnabled(en_ds);
}

private void ShowInventoryCollection(List <Inventory> tmpList) {
    JLabel[] tmpLabels = new JLabel[tmpList.size()+2];
    tmpLabels[0] = new JLabel("  ID         Description        Price    Quant. Res.");
    tmpLabels[0].setFont(new Font("Monospaced", Font.PLAIN, 11));
    tmpLabels[1] = new JLabel("----------------------------------------------------");
    tmpLabels[1].setFont(new Font("Monospaced", Font.PLAIN, 11));
    
    int tmpInt = 2;
    for (Inventory tmpInv : tmpList) {
       String tmpOutStr = String.format("%5s  %20s  %8.2f  %5s  %5s",
               tmpInv.getId(), tmpInv.getDescription(), tmpInv.getPrice().doubleValue(), 
               tmpInv.getInstock(), tmpInv.getReserved()); 
       tmpLabels[tmpInt] = new JLabel(tmpOutStr);
       tmpLabels[tmpInt++].setFont(new Font("Monospaced", Font.PLAIN, 11));
    }
    
    JOptionPane.showMessageDialog(null, tmpLabels, "Search", JOptionPane.PLAIN_MESSAGE);
}

private void ShowUserCollection(List <User> tmpList) {
    JLabel[] tmpLabels = new JLabel[tmpList.size()+2];
    tmpLabels[0] = new JLabel("  ID         First Name        Last Name");
    tmpLabels[0].setFont(new Font("Monospaced", Font.PLAIN, 11));
    tmpLabels[1] = new JLabel("----------------------------------------------------");
    tmpLabels[1].setFont(new Font("Monospaced", Font.PLAIN, 11));
    
    int tmpInt = 2;
    for (User tmpInv : tmpList) {
       String tmpOutStr = String.format("%5s  %20s  %20s",
               tmpInv.getId(), tmpInv.getFirstName(), tmpInv.getLastName()); 
       tmpLabels[tmpInt] = new JLabel(tmpOutStr);
       tmpLabels[tmpInt++].setFont(new Font("Monospaced", Font.PLAIN, 11));
    }
    
    JOptionPane.showMessageDialog(null, tmpLabels, "Search", JOptionPane.PLAIN_MESSAGE);
}

private void ShowCartCollection(List <Cart> tmpList) {
    JLabel[] tmpLabels = new JLabel[tmpList.size()+2];
    tmpLabels[0] = new JLabel("  ID         User ID        Inv ID        Count");
    tmpLabels[0].setFont(new Font("Monospaced", Font.PLAIN, 11));
    tmpLabels[1] = new JLabel("----------------------------------------------------");
    tmpLabels[1].setFont(new Font("Monospaced", Font.PLAIN, 11));
    
    int tmpInt = 2;
    for (Cart tmpInv : tmpList) {
       String tmpOutStr = String.format("%5s  %10s  %12s  %12s",
               tmpInv.getId(), tmpInv.getUserID(), tmpInv.getInvID(), tmpInv.getCount()); 
       tmpLabels[tmpInt] = new JLabel(tmpOutStr);
       tmpLabels[tmpInt++].setFont(new Font("Monospaced", Font.PLAIN, 11));
    }
    
    JOptionPane.showMessageDialog(null, tmpLabels, "Search", JOptionPane.PLAIN_MESSAGE);
}

	
private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
    if (userSess == null) return;
    try {
    	boolean isLoggedIn = userSess.logIn(textFirstName.getText(), textLastName.getText());
    	EnableDisableCtrls(isLoggedIn);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnLogInActionPerformed

private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
    EnableDisableCtrls(false);
}//GEN-LAST:event_btnLogOutActionPerformed

private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    try {
        Integer tmpId = new Integer(textIdCreate.getText());
        Integer tmpCountCreate = new Integer(textCountCreate.getText());
	Double tmpPriceCreate = new Double(textPriceCreate.getText());
	userSess.addPart(tmpId, textDescriptionCreate.getText(), tmpPriceCreate, tmpCountCreate);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCreateActionPerformed

private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
    try {
        Integer tmpId = new Integer(textIdReserve.getText());
        Integer tmpCountRes = new Integer(textCountReserve.getText());
	userSess.reservePart(tmpId, tmpCountRes);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnReserveActionPerformed

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    try {
        List <Inventory> tmpInvList = userSess.searchPartByDescription(textDescriptionSearch.getText());
        ShowInventoryCollection(tmpInvList);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnSearchActionPerformed

private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
    try {
        List <Inventory> tmpInvList = userSess.getAllParts();
        ShowInventoryCollection(tmpInvList);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnShowAllActionPerformed

private void btnCalcTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcTotalActionPerformed
    try {
    	Double tmpTotal = userSess.calculateTotal();
    	JOptionPane.showMessageDialog(null, String.format("%8.2f", tmpTotal), "Total", JOptionPane.PLAIN_MESSAGE);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCalcTotalActionPerformed

private void btnCalcBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcBalanceActionPerformed
    try {
    	Double tmpBalance = userSess.calculateBalance();
    	JOptionPane.showMessageDialog(null, String.format("%8.2f", tmpBalance), "Balance", JOptionPane.PLAIN_MESSAGE);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCalcBalanceActionPerformed

private void btnCalcReservedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcReservedActionPerformed
    try {
    	Double tmpReserved = userSess.calculateReserved();
    	JOptionPane.showMessageDialog(null, String.format("%8.2f", tmpReserved), "Reserved", JOptionPane.PLAIN_MESSAGE);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCalcReservedActionPerformed

    private void btnReserve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserve3ActionPerformed
        try {
            boolean isDeleted = userSess.deletePartByID(new Integer(textIdReserve3.getText()));
            if (isDeleted){
                            JOptionPane.showMessageDialog(null, "Deleted", "Deleted", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReserve3ActionPerformed

    private void textIdReserve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdReserve3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdReserve3ActionPerformed

    private void btnShowAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAll1ActionPerformed
    try {
        List <User> tmpInvList = userSess.getAllUsers();
        ShowUserCollection(tmpInvList);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowAll1ActionPerformed

    private void btnSearchLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLnameActionPerformed
        try {
        List <User> tmpUserList = userSess.searchUserByLName(textSearchLname.getText());
            ShowUserCollection(tmpUserList);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchLnameActionPerformed

    private void btnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNameActionPerformed
        try {
            List <User> tmpUserList = userSess.searchUserByName(textSearchName.getText());
                ShowUserCollection(tmpUserList);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchNameActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
         try {
            boolean isDeleted = userSess.deleteUserByID(new Integer(textDeleteUserID.getText()));
            if(isDeleted){
                JOptionPane.showMessageDialog(null, "Deleted", "Deleted", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        try {
            Integer tmpId = new Integer(textIdCreateUser.getText());
            String tmpName = textFname.getText();
            String tmpLName = textLname.getText();
            userSess.addUser(tmpId, tmpName, tmpLName);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnCreateCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCartActionPerformed
        try {
            Integer tmpId = new Integer(textIdCreateCart.getText());
            Integer tmpUserID = new Integer(textIdCreateCartUserID.getText());
            Integer tmpInvID = new Integer(textIdCreateCartInvID.getText());
            Integer tmpCount = new Integer(textCreateCartCount.getText());
            userSess.addItemToCart(tmpId, tmpUserID, tmpInvID, tmpCount);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateCartActionPerformed

    private void btnSearchCartInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCartInvActionPerformed
        try {
            List <Cart> tmpUserList = userSess.findAllItemsInCartByItemID(new Integer(textSearchCartInv.getText()));
                ShowCartCollection(tmpUserList);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchCartInvActionPerformed

    private void textIdDeleteCartIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdDeleteCartIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdDeleteCartIDActionPerformed

    private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCartActionPerformed
        try {
            boolean isDeleted = userSess.deleteItemFromCart(new Integer(textIdDeleteCartID.getText()));
            if(isDeleted){
                JOptionPane.showMessageDialog(null, "Deleted", "Deleted", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteCartActionPerformed

    private void btnSearchCartUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCartUserActionPerformed
        try {
            List <Cart> tmpUserList = userSess.findAllUserItemsInCartByUserID(new Integer(textSearchCartUser.getText()));
                ShowCartCollection(tmpUserList);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchCartUserActionPerformed

    private void btnGetAllCartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllCartsActionPerformed
        try {
        List <Cart> tmpInvList = userSess.getAllCartItems();
        ShowCartCollection(tmpInvList);
    }
    catch (Exception ex) {
    	JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGetAllCartsActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        try {
            boolean isDeleted = userSess.buyByUserID(new Integer(textBuyUserID.getText()));
            if(isDeleted){
                JOptionPane.showMessageDialog(null, "Bought", "Bought", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryDesktopApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCalcBalance;
    private javax.swing.JButton btnCalcReserved;
    private javax.swing.JButton btnCalcTotal;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateCart;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDeleteCart;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnGetAllCarts;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnReserve3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchCartInv;
    private javax.swing.JButton btnSearchCartUser;
    private javax.swing.JButton btnSearchLname;
    private javax.swing.JButton btnSearchName;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnShowAll1;
    private javax.swing.JPanel jContentPane;
    private javax.swing.JPanel jInventoryChangePanel;
    private javax.swing.JPanel jInventoryChangePanel1;
    private javax.swing.JPanel jInventoryChangePanel2;
    private javax.swing.JPanel jInventoryInfoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLogInPanel;
    private javax.swing.JTextField textBuyUserID;
    private javax.swing.JTextField textCountCreate;
    private javax.swing.JTextField textCountReserve;
    private javax.swing.JTextField textCreateCartCount;
    private javax.swing.JTextField textDeleteUserID;
    private javax.swing.JTextField textDescriptionCreate;
    private javax.swing.JTextField textDescriptionSearch;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textFname;
    private javax.swing.JTextField textIdCreate;
    private javax.swing.JTextField textIdCreateCart;
    private javax.swing.JTextField textIdCreateCartInvID;
    private javax.swing.JTextField textIdCreateCartUserID;
    private javax.swing.JTextField textIdCreateUser;
    private javax.swing.JTextField textIdDeleteCartID;
    private javax.swing.JTextField textIdReserve;
    private javax.swing.JTextField textIdReserve3;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textLname;
    private javax.swing.JTextField textPriceCreate;
    private javax.swing.JTextField textSearchCartInv;
    private javax.swing.JTextField textSearchCartUser;
    private javax.swing.JTextField textSearchLname;
    private javax.swing.JTextField textSearchName;
    // End of variables declaration//GEN-END:variables

}
